# Generated by Django 4.2.5 on 2024-08-31 21:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Tournament',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Section',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('tournament', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sections', to='RestAPI.tournament')),
            ],
        ),
        migrations.CreateModel(
            name='Player',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('rating', models.IntegerField()),
                ('uscf_expiration', models.DateField(blank=True, null=True)),
                ('see_td_flag', models.BooleanField(default=False)),
                ('state', models.CharField(blank=True, max_length=2, null=True)),
                ('team', models.CharField(blank=True, max_length=100, null=True)),
                ('section', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='players', to='RestAPI.section')),
            ],
        ),
        migrations.CreateModel(
            name='Game',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('result', models.FloatField()),
                ('date_played', models.DateTimeField()),
                ('round', models.IntegerField()),
                ('player_black', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='black_games', to='RestAPI.player')),
                ('player_white', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='white_games', to='RestAPI.player')),
                ('tournament', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='games', to='RestAPI.tournament')),
            ],
        ),
    ]
