# Generated by Django 4.2.5 on 2024-09-01 02:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('RestAPI', '0002_rename_name_tournament_title_remove_game_date_played_and_more'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Game',
            new_name='Games',
        ),
        migrations.RenameModel(
            old_name='Player',
            new_name='Players',
        ),
        migrations.RenameModel(
            old_name='Section',
            new_name='Sections',
        ),
        migrations.RenameField(
            model_name='sections',
            old_name='name',
            new_name='title',
        ),
    ]
