# Generated by Django 4.2.5 on 2024-09-01 02:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('RestAPI', '0003_rename_game_games_rename_player_players_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='games',
            name='player',
            field=models.ForeignKey(default=-1, on_delete=django.db.models.deletion.CASCADE, related_name='games', to='RestAPI.players'),
        ),
        migrations.AddField(
            model_name='players',
            name='section',
            field=models.ForeignKey(default=-1, on_delete=django.db.models.deletion.CASCADE, related_name='players', to='RestAPI.sections'),
        ),
    ]
