# Generated by Django 4.2.5 on 2024-09-01 03:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('RestAPI', '0004_games_player_players_section'),
    ]

    operations = [
        migrations.AddField(
            model_name='players',
            name='tournament',
            field=models.ForeignKey(default=-1, on_delete=django.db.models.deletion.CASCADE, related_name='players', to='RestAPI.tournament'),
        ),
        migrations.AlterField(
            model_name='games',
            name='player',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='games', to='RestAPI.players'),
        ),
        migrations.AlterField(
            model_name='players',
            name='section',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='players', to='RestAPI.sections'),
        ),
    ]
