# Generated by Django 4.2.5 on 2024-09-01 03:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('RestAPI', '0005_players_tournament_alter_games_player_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='games',
            name='p1',
            field=models.ForeignKey(default=-1, on_delete=django.db.models.deletion.CASCADE, related_name='player1', to='RestAPI.players'),
        ),
        migrations.AlterField(
            model_name='games',
            name='p2',
            field=models.ForeignKey(default=-1, on_delete=django.db.models.deletion.CASCADE, related_name='player2', to='RestAPI.players'),
        ),
    ]
