# Generated by Django 4.2.5 on 2024-09-01 04:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('RestAPI', '0007_remove_games_p1_remove_games_p2_remove_games_player_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='games',
            name='p1',
            field=models.IntegerField(default=-1),
        ),
        migrations.AddField(
            model_name='games',
            name='p2',
            field=models.IntegerField(default=-1),
        ),
    ]
